### ISSUE TITLE
Install SDK without winget

### ISSUE THREAD

**Issue by boozook** [pd-rs/get-playdate-sdk#21]
Find a way to install SDK without winget, ideally it could be direct installer execution.

Maybe use [this one](https://github.com/idleberg/scoop-playdate-sdk)?..

**Comment by idleberg** [comment]
Have you considered simply controlling the Playdate SDK's installer using available [NSIS flags](https://nsis.sourceforge.io/Docs/Chapter3.html#installerusagecommon)?

I have not tested the following snippet, since I currently don't have access to PowerShell. This example should merely illustrate how this _could_ work.

```powershell
Invoke-WebRequest "https://download.panic.com/playdate_sdk/Windows/PlaydateSDK-$($env:PLAYDATE_SDK_VERSION).exe" -OutFile "$($env:TEMP)/PlayDateSDK.exe"
Start-Process -FilePath "$($env:TEMP)/PlayDateSDK.exe" -ArgumentList "/S","/D=$($env:PLAYDATE_SDK_PATH)"
```

**Comment by boozook** [comment]
@idleberg, thanks! 👍
